//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace megazlo.Res.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Post {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Post() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("megazlo.Res.Model.Post", typeof(Post).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Cat {
            get {
                return ResourceManager.GetString("Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string DatePost {
            get {
                return ResourceManager.GetString("DatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В меню категории.
        /// </summary>
        public static string InCatMenu {
            get {
                return ResourceManager.GetString("InCatMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешить комментировать.
        /// </summary>
        public static string IsCommentable {
            get {
                return ResourceManager.GetString("IsCommentable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать сведения.
        /// </summary>
        public static string IsShowInfo {
            get {
                return ResourceManager.GetString("IsShowInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string R_Text_E {
            get {
                return ResourceManager.GetString("R_Text_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string R_Title_E {
            get {
                return ResourceManager.GetString("R_Title_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
