//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace megazlo.Res.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("megazlo.Res.Model.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string C_ConfirmPassWord_E {
            get {
                return ResourceManager.GetString("C_ConfirmPassWord_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение пароля.
        /// </summary>
        public static string ConfirmPassWord {
            get {
                return ResourceManager.GetString("ConfirmPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string DateBorn {
            get {
                return ResourceManager.GetString("DateBorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации.
        /// </summary>
        public static string DateRegister {
            get {
                return ResourceManager.GetString("DateRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аватара (максимальный размер изображения 200Кб).
        /// </summary>
        public static string HaveAvatar {
            get {
                return ResourceManager.GetString("HaveAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ник (требуется для авторизации).
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string IsAdmin {
            get {
                return ResourceManager.GetString("IsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум 200.
        /// </summary>
        public static string ML_Email_E {
            get {
                return ResourceManager.GetString("ML_Email_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум 100.
        /// </summary>
        public static string ML_Family_E {
            get {
                return ResourceManager.GetString("ML_Family_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум 100.
        /// </summary>
        public static string ML_LastName_E {
            get {
                return ResourceManager.GetString("ML_LastName_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимум 100.
        /// </summary>
        public static string ML_Name_E {
            get {
                return ResourceManager.GetString("ML_Name_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string R_ConfirmPassWord_E {
            get {
                return ResourceManager.GetString("R_ConfirmPassWord_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string R_Email_E {
            get {
                return ResourceManager.GetString("R_Email_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string R_Login_E {
            get {
                return ResourceManager.GetString("R_Login_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string R_Name_E {
            get {
                return ResourceManager.GetString("R_Name_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо заполнить.
        /// </summary>
        public static string R_PassWord_E {
            get {
                return ResourceManager.GetString("R_PassWord_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный email.
        /// </summary>
        public static string RE_Email_E {
            get {
                return ResourceManager.GetString("RE_Email_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина должна быть от 2 до 100.
        /// </summary>
        public static string SL_Login_E {
            get {
                return ResourceManager.GetString("SL_Login_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длина должна быть от 6 до 32.
        /// </summary>
        public static string SL_PassWord_E {
            get {
                return ResourceManager.GetString("SL_PassWord_E", resourceCulture);
            }
        }
    }
}
